services:
  odoo:
    image: odoo:18.0
    container_name: odoo18
    environment:
      HOST: ${ODOO_HOST}
      USER: ${ODOO_USER}
      PASSWORD: ${ODOO_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - data:/var/lib/odoo
      - ./addons:/mnt/extra-addons:rw
  postgres:
    image: postgres:14
    container_name: postgres14-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: ${PGDATA}
    volumes:
      - db:/var/lib/postgresql/data/pgdata
volumes:
  data:
  db:
