services:
  odoo:
    image: ghcr.io/erikngigi/odoo:18
    container_name: odoo18
    environment:
      HOST: ${ODOO_HOST}
      USER: ${ODOO_USER}
      PASSWORD: ${ODOO_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - odoo-volume:/var/lib/odoo
      - ./addons:/mnt/extra-addons:ro
  postgres:
    image: postgres:14
    container_name: postgres14-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: ${PGDATA}
    volumes:
      - postgres-volume:/var/lib/postgresql/data/pgdata
volumes:
  odoo-volume:
    name: odoo18-data-volume
  postgres-volume:
    name: postgres-data-volume
